from cellpose import io, models, metrics, plot
from pathlib import Path
from subprocess import check_output, STDOUT
import os, shutil
import numpy as np


def test_shape_2D():
    """
    Test the output shape of the Cellpose model for 2D images.

        This function creates a dummy 2D image of size 224x224 and evaluates it
        using the Cellpose model in 'cyto3' mode. It asserts that the output
        mask has the expected shape of (224, 224).

        Args:
            None

        Returns:
            None
    """
    img = np.zeros((224, 1, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(img, diameter=30, channels=[0, 0], channel_axis=1)
    assert masks.shape == (224, 224)


def test_shape_3D():
    """
    Tests the shape of the masks produced by the Cellpose model on a 3D input.

        This method creates a 3D image of zeros and uses the Cellpose model for segmentation.
        It verifies that the output masks have the expected shape corresponding to the input.

        Returns:
            None: This function does not return a value, but asserts that the shape of the
            generated masks is as expected.

        Raises:
            AssertionError: If the shape of the generated masks does not match the expected
            shape of (5, 224, 224).
    """
    img = np.zeros((224, 224, 1, 5, 1))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(
        img, diameter=30, channels=[0, 0], channel_axis=None, z_axis=3
    )
    assert masks.shape == (5, 224, 224)


def test_shape_stitch():
    """
    Tests the shape of the masks generated by the Cellpose model during evaluation.

        This method creates a zero-filled image tensor, evaluates the Cellpose model
        with specific parameters, and asserts that the shape of the output masks matches
        the expected dimensions based on the input image.

        Parameters:
            None

        Returns:
            None: This method does not return any value. It raises an assertion error
            if the shape of the masks does not match the expected dimensions.
    """
    img = np.zeros((5, 224, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(
        img, diameter=30, channels=[0, 0], stitch_threshold=0.9
    )
    assert masks.shape == (5, 224, 224)


def test_shape_2D_2chan():
    """
    Test the shape of the output masks from the Cellpose model.

        This method initializes a zero image of shape (224, 3, 224) and utilizes
        the Cellpose model to evaluate the image and generate masks. It asserts
        that the shape of the resulting masks is (224, 224).

        Parameters:
            None

        Returns:
            None
    """
    img = np.zeros((224, 3, 224))
    model = models.Cellpose(model_type="cyto3")
    masks, flows, _, _ = model.eval(img, diameter=30, channels=[2, 1], channel_axis=1)
    assert masks.shape == (224, 224)
